// Writes the build stamp the app header shows, so the running copy can always
// be identified. Regenerated on every build; committed so the packaged app and
// the repository agree on what was shipped.
const fs = require("fs");
const path = require("path");
const { version } = require("../package.json");
const d = new Date();
const p = (n) => String(n).padStart(2, "0");
const stamp = d.getUTCFullYear() + "-" + p(d.getUTCMonth() + 1) + "-" + p(d.getUTCDate()) + " " + p(d.getUTCHours()) + ":" + p(d.getUTCMinutes()) + " UTC";
const out = path.join(__dirname, "..", "src", "build-info.js");
fs.writeFileSync(out, "// Generated by scripts/stamp.js on every build — do not edit by hand.\nexport const BUILD_VERSION = " + JSON.stringify(version) + ";\nexport const BUILD_DATE = " + JSON.stringify(stamp) + ";\n");
console.log("build stamp: v" + version + " · " + stamp);
